###################################################################################
###################################################################################
### ______                             _   _                 ___  ______ _____  ###
##  | ___ \                           | | | |               / _ \ | ___ \_   _|  ##
##  | |_/ / _____      ___   _ ___ ___| |_| | ___  ___  ___/ /_\ \| |_/ / | |    ##
##  | ___ \/ _ \ \ /\ / / | | / __/ __| __| |/ _ \/ __|/ _ \  _  ||  __/  | |    ##
##  | |_/ /  __/\ V  V /| |_| \__ \__ \ |_| | (_) \__ \  __/ | | || |    _| |_   ##
##  \____/ \___| \_/\_/  \__,_|___/___/\__|_|\___/|___/\___\_| |_/\_|    \___/   ##
###                                                                             ###
###################################################################################                                                                        
################################################################################### 
enable-api: false
# database types are 'local' and 'online'.
database: 'online'
#If you do not use an online MySQL Database, you dont need to fill mysql-*
mysql-host: 'localhost'
mysql-user: 'user'
mysql-password: 'password'
mysql-database: 'database'
mysql-port: 3306
#autoupdater does not work yet
auto-updater: false
#modules are in work
modules: false